from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 501, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Request = QtWidgets.QWidget()
        self.Request.setObjectName("Request")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.Request)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 10, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.Request)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.Request)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 40, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.Request)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setLineWidth(0)
        self.label_10.setMidLineWidth(0)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Request)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setLineWidth(0)
        self.label_11.setMidLineWidth(0)
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.Request)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 70, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.Request)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(0)
        self.label_12.setMidLineWidth(0)
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.Request)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.Request, "")
        self.Pull = QtWidgets.QWidget()
        self.Pull.setObjectName("Pull")
        self.lineEdit = QtWidgets.QLineEdit(self.Pull)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.Pull)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Pull)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(0)
        self.label_2.setMidLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Pull)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(0)
        self.label_3.setMidLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Pull)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(0)
        self.label_4.setMidLineWidth(0)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Pull)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(0)
        self.label_5.setMidLineWidth(0)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Pull)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 40, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Pull)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 70, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Pull)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 100, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.Pull)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 130, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.Pull)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Pull, "")
        self.Database = QtWidgets.QWidget()
        self.Database.setObjectName("Database")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Database)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 10, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.Database)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.Database)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(0)
        self.label_6.setMidLineWidth(0)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Database)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(0)
        self.label_7.setMidLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Database)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(0)
        self.label_8.setMidLineWidth(0)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Database)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(0)
        self.label_9.setMidLineWidth(0)
        self.label_9.setObjectName("label_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.Database)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 100, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.comboBox = QtWidgets.QComboBox(self.Database)
        self.comboBox.setGeometry(QtCore.QRect(130, 40, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.Database)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 70, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_2.setMinimumContentsLength(0)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tabWidget.addTab(self.Database, "")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(506, 129, 221, 213))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C/Downloads/1146px-Duke_Athletics_logo.svg.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HealthE Track"))
        self.pushButton_3.setText(_translate("MainWindow", "Get URL"))
        self.label_10.setText(_translate("MainWindow", "URL"))
        self.label_11.setText(_translate("MainWindow", "First Name"))
        self.label_12.setText(_translate("MainWindow", "Last Name"))
        self.pushButton_4.setText(_translate("MainWindow", "Get Token"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Request), _translate("MainWindow", "Token Request"))
        self.label.setText(_translate("MainWindow", "Access Token"))
        self.label_2.setText(_translate("MainWindow", "Access Secret"))
        self.label_3.setText(_translate("MainWindow", "Summary Type"))
        self.label_4.setText(_translate("MainWindow", "Upload Start Time"))
        self.label_5.setText(_translate("MainWindow", "Upload End Time"))
        self.pushButton.setText(_translate("MainWindow", "Pull"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Pull), _translate("MainWindow", "Pull Data"))
        self.pushButton_2.setText(_translate("MainWindow", "Go"))
        self.label_6.setText(_translate("MainWindow", "Access Token"))
        self.label_7.setText(_translate("MainWindow", "Summary Type"))
        self.label_8.setText(_translate("MainWindow", "File Name"))
        self.label_9.setText(_translate("MainWindow", "Request Type"))
        self.comboBox.setCurrentText(_translate("MainWindow", "dailies"))
        self.comboBox.setItemText(0, _translate("MainWindow", "dailies"))
        self.comboBox.setItemText(1, _translate("MainWindow", "epochs"))
        self.comboBox.setItemText(2, _translate("MainWindow", "thirdPartyDailies"))
        self.comboBox.setItemText(3, _translate("MainWindow", "activities"))
        self.comboBox.setItemText(4, _translate("MainWindow", "manuallyUpdatedActivites"))
        self.comboBox.setItemText(5, _translate("MainWindow", "activityDetails"))
        self.comboBox.setItemText(6, _translate("MainWindow", "sleeps"))
        self.comboBox.setItemText(7, _translate("MainWindow", "bodyComps"))
        self.comboBox.setItemText(8, _translate("MainWindow", "stressDetails"))
        self.comboBox.setItemText(9, _translate("MainWindow", "userMetrics"))
        self.comboBox.setItemText(10, _translate("MainWindow", "moveiq"))
        self.comboBox.setItemText(11, _translate("MainWindow", "pulseOx"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "GET"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "POST"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "PUT"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Database), _translate("MainWindow", "Access Database"))
        self.label_14.setText(_translate("MainWindow", "HealthE Track"))


